# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
# system libraries:
#   libcurl -- needed to complete setup-renv
#   libharfbuzz-dev libfribidi-dev -- needed for the textshaping package
#     which is a dependency of ragg, which is a dependency of the new tidyverse (2.0.0)

on:
  pull_request:
  push:
    branches:
      - main
      - dev
      - testing-setup

name: Test

jobs:
  test:
    runs-on: ubuntu-latest

    name: shiny-test-automation

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      
    steps:
      - uses: actions/checkout@v4
      
      - name: Update and upgrade packages
        run: sudo apt-get update && sudo apt-get upgrade -y

      - name: install needed system libs
        shell: bash
        run: |
          sudo apt install libcurl4-openssl-dev libharfbuzz-dev libfribidi-dev
          
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2'
          
      - uses: r-lib/actions/setup-renv@v2
      
      - name: Find PhantomJS path
        id: phantomjs
        run: |
          echo "path=$(Rscript -e 'cat(shinytest:::phantom_paths()[[1]])')" >> $GITHUB_OUTPUT
          
      - name: Cache PhantomJS
        uses: actions/cache@v3
        with:
          path: ${{ steps.phantomjs.outputs.path }}
          key: ${{ runner.os }}-phantomjs
          restore-keys: ${{ runner.os }}-phantomjs
          
      - name: Install PhantomJS
        shell: Rscript {0}
        run: |
          options(install.packages.check.source = "no")
          if (!shinytest::dependenciesInstalled()) shinytest::installDependencies()        

      - name: Run tests
        run: |
          Rscript tests/shinytest.R
          
      - name: Upload test results
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: ${{ runner.os }}-4.2-tests
          path: tests
