# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  pull_request:

name: Test

jobs:
  test:
    runs-on: ubuntu-latest

    name: shiny-test-automation

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      
    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2'

      - name: Set RENV_PATHS_ROOT
        shell: bash
        run: |
          echo "RENV_PATHS_ROOT=${{ runner.temp }}/Library/renv" >> $GITHUB_ENV
          
      - name: Install renv
        run: |
          Rscript -e 'install.packages("renv")'
      
      - name: Cache renv library
        uses: actions/cache@v3
        with:
          path: ${{ env.RENV_PATHS_ROOT }}
          key: ${{ runner.os }}-renv-${{ hashFiles('renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-
            ${{ runner.os }}-
          fail-on-cache-miss: false
