# Workflow derived from https://github.com/rstudio/shinytest2/tree/main/actions/test-app/example-test-app-description.yaml
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
  pull_request:

name: Test2

jobs:
  test:
    runs-on: ubuntu-latest

    name: shiny-test-automation

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      RENV_PATHS_CACHE: '~/.cache/R/renv/cache'
      
    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2'
        
      - name: Setup renv
        uses: r-lib/actions/setup-renv@v2
      
      # - name: Install renv
      #   run: |
      #     Rscript -e 'install.packages("renv")'
      # 
      # - name: Restore renv library
      #   uses: actions/cache@v3
      #   with:
      #     path: ${{ env.RENV_PATHS_CACHE }}
      #     key: ${{ runner.os }}-renv-${{ hashFiles('renv.lock') }}
      #     restore-keys: |
      #       ${{ runner.os }}-renv-
      #       ${{ runner.os }}-
          
      # - name: Merge feature branch with dev
      #   run: |
      #     git config user.email "github-actions[bot]@users.noreply.github.com"
      #     git config user.name "GitHub Actions"
      #     git fetch origin dev
      #     git merge origin/dev
      #     
      # - name: Run tests
      #   run: |
      #     Rscript tests/shinytest.R
