# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
# system libraries:
#   libcurl -- needed to complete setup-renv
#   libharfbuzz-dev libfribidi-dev -- needed for the textshaping package
#     which is a dependency of ragg, which is a dependency of the new tidyverse (2.0.0)

on:
  pull_request:
  push:
    branches:
      - main
      - dev
      - testing-setup

name: Test

jobs:
  test:
    runs-on: ubuntu-latest

    name: shiny-test-automation

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'renv'

      - name: install needed system libs
        shell: bash
        run: |
          sudo apt install libcurl4-openssl-dev libharfbuzz-dev libfribidi-dev
              
      - uses: r-lib/actions/setup-renv@v2
