# Workflow derived from https://github.com/rstudio/shinytest2/tree/main/actions/test-app/example-test-app-description.yaml
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
  pull_request:

name: Test2

jobs:
  test:
    runs-on: ubuntu-latest

    name: shiny-test-automation

    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2'
        
      - name: Install renv
        run: |
          Rscript -e 'install.packages("renv")'
      
      - name: Restore renv library
        run: |
          Rscript -e 'renv::restore()'
          
      - name: Merge feature branch with dev
        run: |
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "GitHub Actions"
          git fetch origin dev
          git merge origin/dev
          
      - name: Run tests
        run: |
          Rscript tests/shinytest.R
