on:
  pull_request:
    branches: [dev, main]
  
name: Test

jobs:
  test0:
    runs-on: ubuntu-latest

    name: font-test-0

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4.1'

      - name: install needed system libs
        shell: bash
        run: |
          sudo apt install libcurl4-openssl-dev libharfbuzz-dev libfribidi-dev
      
      - name: install ragg
        run: |
          install.packages("ragg")
        shell: Rscript {0}

  test1:
    runs-on: ubuntu-latest

    name: font-test-1

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4.1'

      - name: install needed system libs
        shell: bash
        run: |
          sudo apt install libcurl4-openssl-dev libharfbuzz-dev libfribidi-dev libfontconfig1-dev libfreetype6-dev libpng-dev libtiff5-dev libjpeg-dev

      - name: install ggplot with libfontconfig-dev
        run: |
          install.packages("ggplot2")
        shell: Rscript {0}

      - name: Check default font in GHA
        run: |
          echo "Default font in R (ggplot2 theme):"
          Rscript -e "library(ggplot2); print(ggplot2::theme_get()$text$family)"
          echo "Font mapping for 'sans':"
          fc-match sans || echo "fc-match not found"

  test2:
    runs-on: ubuntu-latest

    name: font-test-2

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'renv'

      - name: install needed system libs
        shell: bash
        run: |
          sudo apt install libcurl4-openssl-dev libharfbuzz-dev libfribidi-dev libfreetype6-dev libpng-dev libtiff5-dev libjpeg-dev
              
      - name: install ggplot without libfontconfig-dev
        run: |
          install.packages("ggplot2")
        shell: Rscript {0}

      - name: Check default font in GHA
        run: |
          echo "Default font in R (ggplot2 theme):"
          Rscript -e "library(ggplot2); print(ggplot2::theme_get()$text$family)"
          echo "Font mapping for 'sans':"
          fc-match sans || echo "fc-match not found"